changes in yml file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,15 +1,35 @@
-name: ci demo
+# name: ci demo
+# on: push
+# jobs:
+#   another_test:
+#     runs-on: ubuntu-latest
+#     steps:
+#         - uses: actions/checkout@v4
+#         - run: node index.js
+#         - run: |
+#             if [ -f index.js ]; then
+#                 echo "great file found"
+#             else
+#                 echo "file not found"
+#                 exit 1
+#             fi
+
+
+
+name: node ci cd
+
 on: push
+
 jobs:
-  another_test:
+  node_test:
     runs-on: ubuntu-latest
     steps:
-        - uses: actions/checkout@v4
-        - run: node index.js
-        - run: |
-            if [ -f index.js ]; then
-                echo "great file found"
-            else
-                echo "file not found"
-                exit 1
-            fi
+      - uses: actions/checkout@v4
+      - name: setup node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 22
+      - name: install dependencies
+        run: npm install
+      - name: Run Test
+        run: npm test
